[default]
SQLALCHEMY_DATABASE_URI = "sqlite:///multilens.db"
SQLALCHEMY_TRACK_MODIFICATIONS = false
SESSION_REFRESH_EACH_REQUEST = true
COLOR_THEME = "is-primary"
ORDER_FOLDER = "order"

EXTENSIONS = [
    "multilens.ext.db:init_app",
    "multilens.ext.api:init_app",
    "multilens.ext.auth:init_app",
    "multilens.ext.site:init_app",
    "multilens.ext.admin:init_app",
    "multilens.ext.cli:init_app",
]

[development]
debug=true

[testing]
SQLALCHEMY_DATABASE_URI = "mysql+pymysql://uryei5cidjotscyy:B086DxVHFEwOhFcYBwCO@bct7ziexqm7xot08gxji-mysql.services.clever-cloud.com:3306/bct7ziexqm7xot08gxji"
